### ISSUE TITLE
module 'posix_ipc' has no attribute 'O_RDWR'

### ISSUE THREAD

**Issue by ubgk** [tasts-robots/vulp#21]
I suspect this could require non-trivial modifications to some parts of `vulp`. When I run tests now `vulp/spine/tests/spine_interface_test.py` throws an `AttributeError: module 'posix_ipc' has no attribute 'O_RDWR'`:  (cf. [error.log](https://github.com/tasts-robots/vulp/files/11373131/error.log)).

`O_RDWR` is defined between guards [here](https://github.com/mruffalo/posix_ipc/blob/07fdef7dc8b2b47c09d804fce3c256dcc7fc7f3f/posix_ipc_module.c#L2556), so maybe macOS doesn't implement POSIX message queues?

_Originally posted by @boragokbakan in https://github.com/tasts-robots/vulp/issues/15#issuecomment-1531427156_

**Comment by boragokbakan** [comment]
Oh my bad, nice catch. No idea how I got to the wrong repo. 😅

Do you think this is an easy fix though?

**Comment by stephane-caron** [comment]
@boragokbakan I tried the second option and it performs as before on Linux. We don't need `posix_ipc.O_RDWR` so I expect this issue is fixed, feel free to re-open otherwise.
