### ISSUE TITLE
[macOS] allocate_file fails with ENXIO (errno 6)

### ISSUE THREAD

**Issue by boragokbakan** [tasts-robots/vulp#27]
`SetUp()` in `SpineTest.cpp` (#15) fails due to `ENXIO` (errno 6) thrown by `AgentInterface.cpp:allocate_file`, which means (according to the man entry):

```
      6 ENXIO No such device or address.  Input or output on a special file
             referred to a device that did not exist, or made a request beyond
             the limits of the device.  This error may also occur when, for
             example, a tape drive is not online or no disk pack is loaded on
             a drive.
```

As `AgentInterface` constructor checks for errors after `shm_open`, what do you think could cause the write to fail? @stephane-caron 

You can see the logs here:
[error.log](https://github.com/tasts-robots/vulp/files/11533187/error.log)

**Comment by stephane-caron** [comment]
We can probably fix the first error from the log easily:

```
[2023-05-22 15:36:48.084] [error] Cannot open shared memory "tester": file already exists. Is the spine already running? Did it not exit properly? If not, run ``bazel run @vulp//tools/shm:clean -- tester``
```

This may occur because the tests run in separate threads, but the fixture opens a file named "tester" in shared memory:

```
  void SetUp() override {
    agent_interface_ = std::make_unique<AgentInterface>("tester", 1024);
  }
```

We can work around that with a ``random_string()`` like in the other test fixtures.

**Comment by stephane-caron** [comment]
Closing this issue as fixed by https://github.com/tasts-robots/vulp/pull/30 (we forgot to mark it in the PR).

Feel free to open another issue for the next macOS error.
